Sprint 10
easywinteam/ImageFeed pull request #3
Opened 2023-05-16 11:38 UTC by easywinteam

Домашнее задание по спринту номер 10. Аутентификация и авторизация пользователя в unsplash

2023-05-17 11:20 UTC, IBDesignable requested changes
- Экран AuthViewController сверстан не по макету: оступы от краев у кнопок, размер кнопки выглядят не верными.  Нужно поправить
- Экран авторизации в WebView тоже имеет небольшие отклонения по верстке: видно что progressView и кнопка назад существуют поверх экрана и могут налезать на контент.

2023-05-17 11:20 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +    let WebViewSegueIdentifier = "ShowWebView"
Рекомендуется использовать для всех свойств, аргументов, переменных и методов нижний camelCase

Лучше придерживаться общего гайдлайна по названиям, даже если в учебники авторы используют такой стиль для констант.

2023-05-17 11:20 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +        if segue.identifier == WebViewSegueIdentifier{
у фигурных скобочек должны быть оступы, не должен код сливаться в одну сплошную лапшу:
```suggestion
        if segue.identifier == WebViewSegueIdentifier {
```

2023-05-17 11:20 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +            }
Если guard не влезает в 120 символов в одной строке, то разбиваем его вот так:
```suggestion
            guard
                let webViewViewController = segue.destination as? WebViewViewController 
            else{ 
               fatalError("Failed to prepare for \(WebViewSegueIdentifier)")
            }
```

2023-05-17 11:20 UTC, IBDesignable commented on ImageFeed/Auth/WebViewViewController.swift
> +    @IBOutlet var webView: WKWebView!
тоже приватным можно сделать?

2023-05-17 11:20 UTC, IBDesignable commented on ImageFeed/Auth/WebViewViewController.swift
> +final class WebViewViewController: UIViewController{
```suggestion
final class WebViewViewController: UIViewController {
```

Давай такие помарки проверишь по всему проекту и поправишь если остались еще?

2023-05-17 11:20 UTC, IBDesignable commented on ImageFeed/Auth/WebViewViewController.swift
> +            return codeItem.value
очень слиплось
```suggestion
           let codeItem = items.first(where: { $0.name == "code"} )
       {
            print("****I create code: \(codeItem.value ?? "Nothing")")
            return codeItem.value
```

2023-05-17 11:20 UTC, IBDesignable commented on ImageFeed/Auth/WebViewViewControllerDelegate.swift
> +    func webViewViewController(_ vc: WebViewViewController, didAuthenticateWithCode code: String)
давай договоримся, что больше одной пустой строки в коде не оставляем - так код будет выглядеть и аккуратным, и компактным

2023-05-17 11:20 UTC, IBDesignable commented on ImageFeed/Constants.swift
> +let DefaultBaseURL = URL(string: "https://api.unsplash.com")!
Тоже самое и про эти константы, я рекомендую отступить от кода учебника и пользоваться нижнем camelCase

2023-05-17 11:20 UTC, IBDesignable commented on ImageFeed/OAuth2/OAuth2Service.swift
> +    func fetchOAuthToken(
любой код с фигурными скобками лучше отделять пустыми строчками
```suggestion

    private(set) var authToken: String? {
        get {
            return OAuth2TokenStorage().token
        }
        set {
            OAuth2TokenStorage().token = newValue
        }
    }
    
    func fetchOAuthToken(
```

2023-05-17 11:20 UTC, IBDesignable commented on ImageFeed/OAuth2/OAuth2Service.swift
> +            OAuth2TokenStorage().token = newValue
обращу внимание на вызов `OAuth2TokenStorage()` - этот кусочек по сути создает новый экземпляр класса каждый раз, когда ты его вызываешь.

Не нужно его так дергать в методах, лучше создать объект один раз.
К тому же, помещая внешний сервис внутрь функций (вычислимых свойств, did-set'ов), ты пишешь связынй код. Лучше когда все зависимости четко определены в свойствах класса, это поможет тебе в будущем провести рефакторинг и создавать зависимости правильным образом

Поэтому здесь можно лучше: вынести создание сервиса в отдельное свойство)

2023-05-17 11:20 UTC, IBDesignable commented on ImageFeed/OAuth2/OAuth2Service.swift
> +        ) }
также, обращу внимание, что эту задачу можно решать через URLComponents

2023-05-17 11:20 UTC, IBDesignable commented on ImageFeed/OAuth2/OAuth2Service.swift
> +    } }
Для мапинга данных с сервера, которые используют snake_case кроме подхода с CodingKeys можно еще использовать преднастроенный JSONDecoder, который сам определит как соотнести поле в camelCase с snake_case 

Подробнее тут https://nemecek.be/blog/90/how-to-decode-snake-case-with-codable

2023-05-17 11:20 UTC, IBDesignable commented on ImageFeed/OAuth2/OAuth2Service.swift
> +    } }
замечаю что оставляешь по две фигурные на конце, это не правильно

Закрывающая фигурная должна быть на том же уровне с блоком, который ее открывал (то есть вторая вровень с `extension URLRequest`

2023-05-17 11:20 UTC, IBDesignable commented on ImageFeed/OAuth2/OAuth2TokenStorage.swift
> +            UserDefaults.standard.set(newValue, forKey: tokenKey)
UserDefaults.standard - можно вынести в приватное свойство, выделяя отдельную зависимость

2023-05-17 11:20 UTC, IBDesignable commented on ImageFeed/SplashViewController/SplashViewController.swift
> +    private let oauth2TokenStorage = OAuth2TokenStorage()
здесь все очень хорошо с зависимостями)

2023-05-18 10:31 UTC, easywinteam commented on ImageFeed/OAuth2/OAuth2Service.swift
> +    } }
Хорошо, поправил

2023-05-18 10:33 UTC, easywinteam commented on ImageFeed/Auth/AuthViewController.swift
> +        if segue.identifier == WebViewSegueIdentifier{
Исправил

2023-05-18 18:08 UTC, easywinteam commented on ImageFeed/Auth/AuthViewController.swift
> +    let WebViewSegueIdentifier = "ShowWebView"
Хорошо, спасибо, буду знать на будущее!

2023-05-18 18:18 UTC, easywinteam commented on ImageFeed/Auth/WebViewViewControllerDelegate.swift
> +    func webViewViewController(_ vc: WebViewViewController, didAuthenticateWithCode code: String)
Ок!

2023-05-18 18:18 UTC, easywinteam commented on ImageFeed/Auth/WebViewViewControllerDelegate.swift
> +    func webViewViewController(_ vc: WebViewViewController, didAuthenticateWithCode code: String)
Поправил!

2023-05-18 18:19 UTC, easywinteam commented on ImageFeed/Constants.swift
> +let DefaultBaseURL = URL(string: "https://api.unsplash.com")!
хорошо

2023-05-19 18:55 UTC, IBDesignable commented on ImageFeed/Auth/WebViewViewController.swift
> +final class WebViewViewController: UIViewController{
Осталось не исправленным

2023-05-22 13:12 UTC, easywinteam commented
Sprint was completed and approved

2023-05-22 13:12 UTC, merged